openapi: 3.0.3
info:
    title: LFX V2 - Voting Service
    description: Proxy service for ITX voting system
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /votes:
        post:
            tags:
                - voting
            summary: create_vote voting
            description: Create a new vote (proxies to ITX POST /voting/poll)
            operationId: voting#create_vote
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateVoteRequestBody'
                        example:
                            allow_abstain: true
                            committee_filters:
                                - Voting Rep
                                - Alternate Voting Rep
                            committee_id: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                            description: Vote for the TSC members for Q1 2026
                            end_time: "2026-02-15T23:59:59Z"
                            name: Q1 2026 Technical Steering Committee Election
                            num_winners: 6
                            poll_questions:
                                - choices:
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                  prompt: Who should be elected to the TSC?
                                  question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                                  type: single_choice
                                - choices:
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                  prompt: Who should be elected to the TSC?
                                  question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                                  type: single_choice
                                - choices:
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                    - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                                      choice_text: John Doe
                                  prompt: Who should be elected to the TSC?
                                  question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                                  type: single_choice
                            poll_type: condorcet_irv
                            project_id: a09P000000DsCBuIRT
                            pseudo_anonymity: true
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VoteResult'
                            example:
                                allow_abstain: true
                                committee_id: Sit praesentium sint qui error.
                                committee_name: Sint impedit quo ea ut maiores laudantium.
                                committee_type: Iusto cum est tempora laboriosam eum sapiente.
                                committee_voting_status: true
                                creation_time: "1979-07-05T09:54:25Z"
                                description: Sequi laudantium assumenda.
                                end_time: "1997-11-09T17:02:32Z"
                                last_modified_time: "1985-12-29T03:07:54Z"
                                name: Iusto ut dignissimos.
                                num_response_received: 6574475979321634966
                                poll_id: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                                poll_questions:
                                    - choices:
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                      prompt: Who should be elected to the TSC?
                                      question_id: e6360d94-9368-432f-9e8b-8643b024f862
                                      type: single_choice
                                    - choices:
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                      prompt: Who should be elected to the TSC?
                                      question_id: e6360d94-9368-432f-9e8b-8643b024f862
                                      type: single_choice
                                    - choices:
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                      prompt: Who should be elected to the TSC?
                                      question_id: e6360d94-9368-432f-9e8b-8643b024f862
                                      type: single_choice
                                    - choices:
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                        - choice_id: 3269cd91-1b07-48dd-9587-22a0fbd1f712
                                          choice_text: John Doe
                                      prompt: Who should be elected to the TSC?
                                      question_id: e6360d94-9368-432f-9e8b-8643b024f862
                                      type: single_choice
                                project_id: Est exercitationem qui.
                                pseudo_anonymity: true
                                status: disabled
                                total_voting_request_invitations: 6966395354154532441
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/BadRequestError'
                            example:
                                code: Optio tenetur iure quaerat dolore placeat saepe.
                                message: Autem ratione qui qui asperiores soluta laboriosam.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UnauthorizedError'
                            example:
                                code: Porro quibusdam magnam ipsum voluptas.
                                message: Praesentium adipisci sit.
                "403":
                    description: 'Forbidden: Forbidden'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ForbiddenError'
                            example:
                                code: Omnis nihil quae quae numquam.
                                message: In laborum rerum.
                "409":
                    description: 'Conflict: Conflict'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ConflictError'
                            example:
                                code: Provident quo.
                                message: Fuga perferendis eos quas quod ut.
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InternalServerError'
                            example:
                                code: Adipisci accusamus dolorem maxime nemo sit totam.
                                message: Aliquam praesentium.
                "503":
                    description: 'ServiceUnavailable: Service unavailable'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ServiceUnavailableError'
                            example:
                                code: Voluptatum iste non.
                                message: Iusto ut.
            security:
                - jwt_header_Authorization:
                    - manage:projects
                    - manage:voting
components:
    schemas:
        BadRequestError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Inventore et qui qui eveniet ipsa.
                message:
                    type: string
                    description: Error message
                    example: Beatae laborum.
            description: Bad request error response
            example:
                code: Quam placeat dolores aperiam ut deleniti.
                message: Ipsum blanditiis rerum sit inventore.
            required:
                - code
                - message
        ConflictError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Veniam voluptatibus ullam.
                message:
                    type: string
                    description: Error message
                    example: Deleniti molestiae esse veniam soluta commodi ea.
            description: Conflict error response
            example:
                code: Unde aut libero doloremque vel aliquid autem.
                message: Autem sunt.
            required:
                - code
                - message
        CreateVoteRequestBody:
            type: object
            properties:
                allow_abstain:
                    type: boolean
                    description: Allow voters to abstain
                    default: false
                    example: false
                committee_filters:
                    type: array
                    items:
                        type: string
                        example: Emeritus
                        enum:
                            - Voting Rep
                            - Alternate Voting Rep
                            - Observer
                            - Emeritus
                    description: Committee voting status filters
                    example:
                        - Voting Rep
                        - Alternate Voting Rep
                committee_id:
                    type: string
                    description: LFX Committee ID
                    example: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                    format: uuid
                description:
                    type: string
                    description: Vote description
                    example: Vote for the TSC members for Q1 2026
                end_time:
                    type: string
                    description: End time in RFC3339 format
                    example: "2026-02-15T23:59:59Z"
                    format: date-time
                name:
                    type: string
                    description: Vote name
                    example: Q1 2026 Technical Steering Committee Election
                    minLength: 1
                    maxLength: 255
                num_winners:
                    type: integer
                    description: Number of winners (meek_stv only)
                    default: 2
                    example: 8
                    format: int64
                    minimum: 2
                    maximum: 10
                poll_questions:
                    type: array
                    items:
                        $ref: '#/components/schemas/PollQuestion'
                    description: Questions for the vote
                    example:
                        - choices:
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                          type: single_choice
                        - choices:
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                          type: single_choice
                        - choices:
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                          type: single_choice
                        - choices:
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                            - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                          type: single_choice
                poll_type:
                    type: string
                    description: Type of poll
                    default: generic
                    example: meek_stv
                    enum:
                        - generic
                        - condorcet_irv
                        - meek_stv
                project_id:
                    type: string
                    description: LFX Project ID
                    example: a09P000000DsCBuIRT
                pseudo_anonymity:
                    type: boolean
                    description: Enable pseudo-anonymity
                    default: false
                    example: true
            example:
                allow_abstain: false
                committee_filters:
                    - Voting Rep
                    - Alternate Voting Rep
                committee_id: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                description: Vote for the TSC members for Q1 2026
                end_time: "2026-02-15T23:59:59Z"
                name: Q1 2026 Technical Steering Committee Election
                num_winners: 3
                poll_questions:
                    - choices:
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                      type: single_choice
                    - choices:
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                      type: single_choice
                    - choices:
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                      type: single_choice
                    - choices:
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                        - choice_id: 55b93540-31c4-43e4-9960-20cd8472f5df
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-b5c6-4a54-b489-bdac8c7d0501
                      type: single_choice
                poll_type: condorcet_irv
                project_id: a09P000000DsCBuIRT
                pseudo_anonymity: false
            required:
                - name
                - description
                - end_time
                - project_id
                - committee_id
                - poll_questions
        ForbiddenError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Aut quia ut iste.
                message:
                    type: string
                    description: Error message
                    example: Consectetur et omnis sint.
            description: Forbidden error response
            example:
                code: Sapiente odit.
                message: Debitis quam doloremque et.
            required:
                - code
                - message
        InternalServerError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Saepe quo quam.
                message:
                    type: string
                    description: Error message
                    example: Et harum quis dolores ipsam officiis.
            description: Internal server error response
            example:
                code: Nihil tempora.
                message: Sit ipsa dolorem nemo corrupti.
            required:
                - code
                - message
        NotFoundError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Inventore libero rerum.
                message:
                    type: string
                    description: Error message
                    example: Sit corrupti hic voluptate qui.
            description: Not found error response
            example:
                code: Quo ut.
                message: Non possimus eos voluptates quidem vero.
            required:
                - code
                - message
        PollChoice:
            type: object
            properties:
                choice_id:
                    type: string
                    description: Choice identifier
                    example: 14747037-58ad-49b4-90d4-e5c91e0b9e40
                    format: uuid
                choice_text:
                    type: string
                    description: Choice text
                    example: John Doe
            description: Answer choice
            example:
                choice_id: 690adde3-df71-48d2-b826-c51dc1e5026f
                choice_text: John Doe
            required:
                - choice_text
        PollQuestion:
            type: object
            properties:
                choices:
                    type: array
                    items:
                        $ref: '#/components/schemas/PollChoice'
                    description: Answer choices
                    example:
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                prompt:
                    type: string
                    description: Question prompt
                    example: Who should be elected to the TSC?
                question_id:
                    type: string
                    description: Question identifier
                    example: 350f90ab-6c77-40b0-96c0-18f8dc35d2b8
                    format: uuid
                type:
                    type: string
                    description: Question type
                    example: single_choice
                    enum:
                        - single_choice
                        - multiple_choice
            description: Vote question
            example:
                choices:
                    - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                      choice_text: John Doe
                    - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                      choice_text: John Doe
                    - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                      choice_text: John Doe
                    - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                      choice_text: John Doe
                prompt: Who should be elected to the TSC?
                question_id: 90b23097-2d1b-4ab8-b186-8452d4155831
                type: single_choice
            required:
                - prompt
                - type
                - choices
        ServiceUnavailableError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Autem placeat.
                message:
                    type: string
                    description: Error message
                    example: Dolores enim aut dolore ullam unde iure.
            description: Service unavailable error response
            example:
                code: Sed temporibus vel et.
                message: Officia earum laudantium commodi.
            required:
                - code
                - message
        UnauthorizedError:
            type: object
            properties:
                code:
                    type: string
                    description: HTTP status code
                    example: Itaque dolores harum blanditiis quaerat ex.
                message:
                    type: string
                    description: Error message
                    example: Dignissimos numquam.
            description: Unauthorized error response
            example:
                code: Incidunt quia.
                message: Omnis esse omnis rerum nam.
            required:
                - code
                - message
        VoteResult:
            type: object
            properties:
                allow_abstain:
                    type: boolean
                    description: Allow abstain
                    example: false
                committee_id:
                    type: string
                    description: Committee ID
                    example: Iste facere quia doloremque officiis omnis.
                committee_name:
                    type: string
                    description: Committee name
                    example: Omnis saepe eum eius amet aut.
                committee_type:
                    type: string
                    description: Committee type
                    example: Ex reiciendis harum natus consectetur suscipit ratione.
                committee_voting_status:
                    type: boolean
                    description: Committee voting status
                    example: true
                creation_time:
                    type: string
                    description: Creation time
                    example: "1985-08-17T10:13:16Z"
                    format: date-time
                description:
                    type: string
                    description: Vote description
                    example: Harum voluptatibus ut voluptas quidem molestias consectetur.
                end_time:
                    type: string
                    description: End time
                    example: "2012-06-16T08:22:34Z"
                    format: date-time
                last_modified_time:
                    type: string
                    description: Last modified time
                    example: "2005-06-06T03:31:04Z"
                    format: date-time
                name:
                    type: string
                    description: Vote name
                    example: Sit porro.
                num_response_received:
                    type: integer
                    description: Responses received
                    example: 7619583436641651303
                    format: int64
                poll_id:
                    type: string
                    description: Vote identifier (ITX poll_id)
                    example: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                    format: uuid
                poll_questions:
                    type: array
                    items:
                        $ref: '#/components/schemas/PollQuestion'
                    description: Vote questions
                    example:
                        - choices:
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 5de700c1-f574-4766-9ebf-bca757ef9343
                          type: single_choice
                        - choices:
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 5de700c1-f574-4766-9ebf-bca757ef9343
                          type: single_choice
                        - choices:
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                            - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                              choice_text: John Doe
                          prompt: Who should be elected to the TSC?
                          question_id: 5de700c1-f574-4766-9ebf-bca757ef9343
                          type: single_choice
                project_id:
                    type: string
                    description: Project ID
                    example: Sapiente fugiat.
                pseudo_anonymity:
                    type: boolean
                    description: Pseudo-anonymity enabled
                    example: true
                status:
                    type: string
                    description: Vote status
                    example: disabled
                    enum:
                        - disabled
                        - active
                        - ended
                total_voting_request_invitations:
                    type: integer
                    description: Total invitations sent
                    example: 5491820807781387194
                    format: int64
            description: Vote details
            example:
                allow_abstain: false
                committee_id: Et itaque ut et consequatur voluptatem vel.
                committee_name: Perspiciatis sed ratione iusto rerum pariatur itaque.
                committee_type: Qui in voluptas quos.
                committee_voting_status: false
                creation_time: "1980-07-28T20:33:26Z"
                description: Vel nobis distinctio sunt deleniti.
                end_time: "1989-12-29T04:42:39Z"
                last_modified_time: "1983-08-30T09:57:43Z"
                name: Pariatur amet.
                num_response_received: 8580183324472389929
                poll_id: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                poll_questions:
                    - choices:
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 5de700c1-f574-4766-9ebf-bca757ef9343
                      type: single_choice
                    - choices:
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                        - choice_id: d0256908-8155-4caf-863b-48885a0e8dbf
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 5de700c1-f574-4766-9ebf-bca757ef9343
                      type: single_choice
                project_id: Magni modi.
                pseudo_anonymity: false
                status: disabled
                total_voting_request_invitations: 4613039769043529539
            required:
                - poll_id
                - name
                - description
                - status
                - project_id
                - committee_id
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Heimdall JWT authorization
            scheme: bearer
tags:
    - name: voting
      description: Voting service that proxies to ITX voting API
