swagger: "2.0"
info:
    title: LFX V2 - Voting Service
    description: Proxy service for ITX voting system
    version: "1.0"
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /votes:
        post:
            tags:
                - voting
            summary: create_vote voting
            description: |-
                Create a new vote (proxies to ITX POST /voting/poll)

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#create_vote
            parameters:
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
                - name: create_vote_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VotingCreateVoteRequestBody'
                    required:
                        - name
                        - description
                        - end_time
                        - project_uid
                        - committee_uid
                        - poll_questions
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/VoteResult'
                        required:
                            - vote_uid
                            - name
                            - description
                            - status
                            - project_uid
                            - committee_uid
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/ConflictError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /votes/{vote_uid}:
        get:
            tags:
                - voting
            summary: get_vote voting
            description: |-
                Get vote details (proxies to ITX GET /voting/poll/{poll_id})

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#get_vote
            parameters:
                - name: vote_uid
                  in: path
                  description: Vote UID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/VoteResult'
                        required:
                            - vote_uid
                            - name
                            - description
                            - status
                            - project_uid
                            - committee_uid
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
        put:
            tags:
                - voting
            summary: update_vote voting
            description: |-
                Update vote (proxies to ITX PUT /voting/poll/{poll_id}). Only allowed when status is 'disabled'

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#update_vote
            parameters:
                - name: vote_uid
                  in: path
                  description: Vote UID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
                - name: update_vote_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VotingUpdateVoteRequestBody'
                    required:
                        - name
                        - description
                        - end_time
                        - poll_questions
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/VoteResult'
                        required:
                            - vote_uid
                            - name
                            - description
                            - status
                            - project_uid
                            - committee_uid
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
        delete:
            tags:
                - voting
            summary: delete_vote voting
            description: |-
                Delete vote (proxies to ITX DELETE /voting/poll/{poll_id}). Only allowed when status is 'disabled'

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#delete_vote
            parameters:
                - name: vote_uid
                  in: path
                  description: Vote UID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /votes/{vote_uid}/bulk_resend:
        post:
            tags:
                - voting
            summary: bulk_resend_vote voting
            description: |-
                Bulk resend vote email to select recipients (proxies to ITX POST /voting/poll/{poll_id}/bulk_resend)

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#bulk_resend_vote
            parameters:
                - name: vote_uid
                  in: path
                  description: Vote UID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
                - name: bulk_resend_vote_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VotingBulkResendVoteRequestBody'
                    required:
                        - recipient_ids
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /votes/{vote_uid}/enable:
        put:
            tags:
                - voting
            summary: enable_vote voting
            description: |-
                Enable a vote for voting (proxies to ITX PUT /voting/poll/{poll_id}/enable)

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#enable_vote
            parameters:
                - name: vote_uid
                  in: path
                  description: Vote UID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /votes/{vote_uid}/extend:
        post:
            tags:
                - voting
            summary: extend_vote voting
            description: |-
                Extend a vote's end time (proxies to ITX POST /voting/poll/{poll_id}/extend)

                **Required security scopes for jwt**:
                  * `manage:projects`
                  * `manage:voting`
            operationId: voting#extend_vote
            parameters:
                - name: vote_uid
                  in: path
                  description: Vote UID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: JWT token
                  required: false
                  type: string
                - name: extend_vote_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VotingExtendVoteRequestBody'
                    required:
                        - end_time
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/VoteResult'
                        required:
                            - vote_uid
                            - name
                            - description
                            - status
                            - project_uid
                            - committee_uid
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequestError'
                        required:
                            - code
                            - message
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - code
                            - message
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/ForbiddenError'
                        required:
                            - code
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - code
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - code
                            - message
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ServiceUnavailableError'
                        required:
                            - code
                            - message
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
definitions:
    BadRequestError:
        title: BadRequestError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Mollitia consequatur ipsam.
            message:
                type: string
                description: Error message
                example: Velit quia suscipit rem ipsam porro.
        description: Bad request
        example:
            code: Aut eos quia vel qui dicta.
            message: Sed ut voluptatibus.
        required:
            - code
            - message
    ConflictError:
        title: ConflictError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Ab et possimus aut.
            message:
                type: string
                description: Error message
                example: Dignissimos quo sunt.
        description: Conflict
        example:
            code: Quas nihil dolore.
            message: Recusandae ut laudantium.
        required:
            - code
            - message
    ForbiddenError:
        title: ForbiddenError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Tempora sunt unde aut possimus quaerat.
            message:
                type: string
                description: Error message
                example: Quos odit commodi sint ullam sequi ipsam.
        description: Forbidden
        example:
            code: Beatae et.
            message: Veniam adipisci dicta.
        required:
            - code
            - message
    InternalServerError:
        title: InternalServerError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Velit voluptatem.
            message:
                type: string
                description: Error message
                example: Et blanditiis itaque natus quaerat atque est.
        description: Internal server error
        example:
            code: Minima iste et.
            message: Vel ut animi.
        required:
            - code
            - message
    NotFoundError:
        title: NotFoundError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Magnam quia temporibus qui pariatur.
            message:
                type: string
                description: Error message
                example: Iste ut culpa ipsam.
        description: Not found
        example:
            code: Quia autem quae et quis.
            message: Enim soluta ut qui voluptas.
        required:
            - code
            - message
    PollChoice:
        title: PollChoice
        type: object
        properties:
            choice_id:
                type: string
                description: Choice identifier
                example: 77058784-cbfd-425f-b737-e1ef589df5b3
                format: uuid
            choice_text:
                type: string
                description: Choice text
                example: John Doe
        description: Answer choice
        example:
            choice_id: 95d1a5fa-0d51-459e-8947-dc31cb47e9c6
            choice_text: John Doe
        required:
            - choice_text
    PollCommentPrompt:
        title: PollCommentPrompt
        type: object
        properties:
            prompt:
                type: string
                description: Comment prompt text
                example: Please provide any additional feedback
        description: Comment prompt for collecting feedback
        example:
            prompt: Please provide any additional feedback
        required:
            - prompt
    PollQuestion:
        title: PollQuestion
        type: object
        properties:
            choices:
                type: array
                items:
                    $ref: '#/definitions/PollChoice'
                description: Answer choices
                example:
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
            prompt:
                type: string
                description: Question prompt
                example: Who should be elected to the TSC?
            question_id:
                type: string
                description: Question identifier
                example: 05e2b461-9dd1-492b-b29e-258219af2be6
                format: uuid
            type:
                type: string
                description: Question type
                example: single_choice
                enum:
                    - single_choice
                    - multiple_choice
        description: Vote question
        example:
            choices:
                - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                  choice_text: John Doe
                - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                  choice_text: John Doe
                - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                  choice_text: John Doe
                - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                  choice_text: John Doe
            prompt: Who should be elected to the TSC?
            question_id: d3c7551a-b823-4e3e-8036-7de3ffdc1488
            type: single_choice
        required:
            - prompt
            - type
            - choices
    ServiceUnavailableError:
        title: ServiceUnavailableError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Enim repellendus placeat dolorem nostrum.
            message:
                type: string
                description: Error message
                example: Et saepe totam autem ut.
        description: Service unavailable
        example:
            code: Libero repellat.
            message: Quaerat quaerat voluptatem eum voluptatem iure et.
        required:
            - code
            - message
    UnauthorizedError:
        title: UnauthorizedError
        type: object
        properties:
            code:
                type: string
                description: HTTP status code
                example: Tenetur officiis illum vel placeat quasi natus.
            message:
                type: string
                description: Error message
                example: Velit tempore sed fugit deserunt necessitatibus.
        description: Unauthorized
        example:
            code: Qui sit debitis harum ut tempora.
            message: Et voluptas nihil dolorem.
        required:
            - code
            - message
    VoteResult:
        title: VoteResult
        type: object
        properties:
            allow_abstain:
                type: boolean
                description: Allow abstain
                example: true
            committee_name:
                type: string
                description: Committee name
                example: Suscipit ratione ut aut.
            committee_type:
                type: string
                description: Committee type
                example: Eius error vel perspiciatis pariatur.
            committee_uid:
                type: string
                description: Committee UID
                example: Aut numquam ex reiciendis harum natus.
            committee_voting_status:
                type: boolean
                description: Committee voting status
                example: false
            creation_time:
                type: string
                description: Creation time
                example: "2005-09-13T04:41:03Z"
                format: date-time
            description:
                type: string
                description: Vote description
                example: Rerum perferendis ex quod harum numquam.
            end_time:
                type: string
                description: End time
                example: "1996-12-25T08:36:38Z"
                format: date-time
            last_modified_time:
                type: string
                description: Last modified time
                example: "1984-12-16T07:02:24Z"
                format: date-time
            name:
                type: string
                description: Vote name
                example: Molestias consectetur iste temporibus.
            num_response_received:
                type: integer
                description: Responses received
                example: 5330836118803411887
                format: int64
            poll_questions:
                type: array
                items:
                    $ref: '#/definitions/PollQuestion'
                description: Vote questions
                example:
                    - choices:
                        - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                          choice_text: John Doe
                        - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 510c35f0-145b-4eed-818b-486dc2b80f16
                      type: single_choice
                    - choices:
                        - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                          choice_text: John Doe
                        - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 510c35f0-145b-4eed-818b-486dc2b80f16
                      type: single_choice
                    - choices:
                        - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                          choice_text: John Doe
                        - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 510c35f0-145b-4eed-818b-486dc2b80f16
                      type: single_choice
            project_uid:
                type: string
                description: Project UID
                example: Eum eius.
            pseudo_anonymity:
                type: boolean
                description: Pseudo-anonymity enabled
                example: true
            status:
                type: string
                description: Vote status
                example: disabled
                enum:
                    - disabled
                    - active
                    - ended
            total_voting_request_invitations:
                type: integer
                description: Total invitations sent
                example: 4797917587653404989
                format: int64
            vote_uid:
                type: string
                description: Vote identifier
                example: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                format: uuid
        example:
            allow_abstain: false
            committee_name: Repudiandae voluptatem reprehenderit officiis sapiente tempore pariatur.
            committee_type: Iste aliquid facilis.
            committee_uid: Quibusdam sunt voluptas sed vero quis unde.
            committee_voting_status: true
            creation_time: "2007-11-02T13:29:05Z"
            description: Quo ut.
            end_time: "1992-07-18T19:40:34Z"
            last_modified_time: "1972-11-03T17:50:49Z"
            name: Hic voluptate qui.
            num_response_received: 8976121667180691541
            poll_questions:
                - choices:
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 510c35f0-145b-4eed-818b-486dc2b80f16
                  type: single_choice
                - choices:
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 510c35f0-145b-4eed-818b-486dc2b80f16
                  type: single_choice
                - choices:
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                    - choice_id: 82eb444d-60fa-4cef-b7bc-a1a754bce298
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 510c35f0-145b-4eed-818b-486dc2b80f16
                  type: single_choice
            project_uid: Est possimus ipsa itaque maiores eos quis.
            pseudo_anonymity: true
            status: disabled
            total_voting_request_invitations: 5533442698434648331
            vote_uid: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
        required:
            - vote_uid
            - name
            - description
            - status
            - project_uid
            - committee_uid
    VotingBulkResendVoteRequestBody:
        title: VotingBulkResendVoteRequestBody
        type: object
        properties:
            recipient_ids:
                type: array
                items:
                    type: string
                    example: Blanditiis quisquam alias laborum.
                description: List of recipient IDs to resend vote email to
                example:
                    - cba14f40-1636-11ec-9621-0242ac130002
                    - cba14f40-1636-11ec-9621-0242ac130003
        example:
            recipient_ids:
                - cba14f40-1636-11ec-9621-0242ac130002
                - cba14f40-1636-11ec-9621-0242ac130003
        required:
            - recipient_ids
    VotingCreateVoteRequestBody:
        title: VotingCreateVoteRequestBody
        type: object
        properties:
            allow_abstain:
                type: boolean
                description: Allow voters to abstain
                default: false
                example: false
            committee_filters:
                type: array
                items:
                    type: string
                    example: Observer
                    enum:
                        - Voting Rep
                        - Alternate Voting Rep
                        - Observer
                        - Emeritus
                description: Committee voting status filters
                example:
                    - Voting Rep
                    - Alternate Voting Rep
            committee_uid:
                type: string
                description: LFX Committee UID
                example: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                format: uuid
            committee_uids:
                type: array
                items:
                    type: string
                    example: Est molestiae cum in labore similique illo.
                description: Multiple committee UIDs
                example:
                    - a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                    - b03cdbaf-53b1-4d47-bc04-dd7e459dd309
            description:
                type: string
                description: Vote description
                example: Vote for the TSC members for Q1 2026
            end_time:
                type: string
                description: End time in RFC3339 format
                example: "2026-02-15T23:59:59Z"
                format: date-time
            name:
                type: string
                description: Vote name
                example: Q1 2026 Technical Steering Committee Election
                minLength: 1
                maxLength: 255
            num_winners:
                type: integer
                description: Number of winners (meek_stv only)
                default: 2
                example: 9
                format: int64
                minimum: 2
                maximum: 10
            poll_comment_prompts:
                type: array
                items:
                    $ref: '#/definitions/PollCommentPrompt'
                description: Comment prompts for the vote
                example:
                    - prompt: Please provide any additional feedback
                    - prompt: Please provide any additional feedback
                    - prompt: Please provide any additional feedback
                    - prompt: Please provide any additional feedback
            poll_questions:
                type: array
                items:
                    $ref: '#/definitions/PollQuestion'
                description: Questions for the vote
                example:
                    - choices:
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                      type: single_choice
                    - choices:
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                      type: single_choice
                    - choices:
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                      type: single_choice
                    - choices:
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                      type: single_choice
            poll_type:
                type: string
                description: Type of poll
                default: generic
                example: meek_stv
                enum:
                    - generic
                    - condorcet_irv
                    - meek_stv
            project_uid:
                type: string
                description: LFX Project UID
                example: a09P000000DsCBuIRT
            pseudo_anonymity:
                type: boolean
                description: Enable pseudo-anonymity
                default: false
                example: true
            quorum_percentage:
                type: integer
                description: Quorum percentage required
                example: 50
                format: int64
                minimum: 0
                maximum: 100
            winning_threshold_percentage:
                type: integer
                description: Winning threshold percentage
                example: 51
                format: int64
                minimum: 0
                maximum: 100
        example:
            allow_abstain: false
            committee_filters:
                - Voting Rep
                - Alternate Voting Rep
            committee_uid: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
            committee_uids:
                - a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                - b03cdbaf-53b1-4d47-bc04-dd7e459dd309
            description: Vote for the TSC members for Q1 2026
            end_time: "2026-02-15T23:59:59Z"
            name: Q1 2026 Technical Steering Committee Election
            num_winners: 4
            poll_comment_prompts:
                - prompt: Please provide any additional feedback
                - prompt: Please provide any additional feedback
                - prompt: Please provide any additional feedback
            poll_questions:
                - choices:
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                  type: single_choice
                - choices:
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                  type: single_choice
            poll_type: meek_stv
            project_uid: a09P000000DsCBuIRT
            pseudo_anonymity: false
            quorum_percentage: 50
            winning_threshold_percentage: 51
        required:
            - name
            - description
            - end_time
            - project_uid
            - committee_uid
            - poll_questions
    VotingExtendVoteRequestBody:
        title: VotingExtendVoteRequestBody
        type: object
        properties:
            end_time:
                type: string
                description: End time in RFC3339 format
                example: "2026-02-15T23:59:59Z"
                format: date-time
        example:
            end_time: "2026-02-15T23:59:59Z"
        required:
            - end_time
    VotingUpdateVoteRequestBody:
        title: VotingUpdateVoteRequestBody
        type: object
        properties:
            allow_abstain:
                type: boolean
                description: Allow voters to abstain
                default: false
                example: true
            committee_filters:
                type: array
                items:
                    type: string
                    example: Emeritus
                    enum:
                        - Voting Rep
                        - Alternate Voting Rep
                        - Observer
                        - Emeritus
                description: Committee voting status filters
                example:
                    - Voting Rep
                    - Alternate Voting Rep
            committee_uid:
                type: string
                description: LFX Committee UID
                example: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                format: uuid
            committee_uids:
                type: array
                items:
                    type: string
                    example: Praesentium debitis nam minima consequatur.
                description: Multiple committee UIDs
                example:
                    - a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                    - b03cdbaf-53b1-4d47-bc04-dd7e459dd309
            description:
                type: string
                description: Vote description
                example: Vote for the TSC members for Q1 2026
            end_time:
                type: string
                description: End time in RFC3339 format
                example: "2026-02-15T23:59:59Z"
                format: date-time
            name:
                type: string
                description: Vote name
                example: Q1 2026 Technical Steering Committee Election
                minLength: 1
                maxLength: 255
            num_winners:
                type: integer
                description: Number of winners (meek_stv only)
                default: 2
                example: 8
                format: int64
                minimum: 2
                maximum: 10
            poll_comment_prompts:
                type: array
                items:
                    $ref: '#/definitions/PollCommentPrompt'
                description: Comment prompts for the vote
                example:
                    - prompt: Please provide any additional feedback
                    - prompt: Please provide any additional feedback
            poll_questions:
                type: array
                items:
                    $ref: '#/definitions/PollQuestion'
                description: Questions for the vote
                example:
                    - choices:
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                      type: single_choice
                    - choices:
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                        - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                          choice_text: John Doe
                      prompt: Who should be elected to the TSC?
                      question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                      type: single_choice
            poll_type:
                type: string
                description: Type of poll
                default: generic
                example: meek_stv
                enum:
                    - generic
                    - condorcet_irv
                    - meek_stv
            project_uid:
                type: string
                description: LFX Project UID
                example: a09P000000DsCBuIRT
            pseudo_anonymity:
                type: boolean
                description: Enable pseudo-anonymity
                default: false
                example: false
            quorum_percentage:
                type: integer
                description: Quorum percentage required
                example: 50
                format: int64
                minimum: 0
                maximum: 100
            winning_threshold_percentage:
                type: integer
                description: Winning threshold percentage
                example: 51
                format: int64
                minimum: 0
                maximum: 100
        example:
            allow_abstain: false
            committee_filters:
                - Voting Rep
                - Alternate Voting Rep
            committee_uid: a02bdbaf-53b1-4d47-bc04-dd7e459dd308
            committee_uids:
                - a02bdbaf-53b1-4d47-bc04-dd7e459dd308
                - b03cdbaf-53b1-4d47-bc04-dd7e459dd309
            description: Vote for the TSC members for Q1 2026
            end_time: "2026-02-15T23:59:59Z"
            name: Q1 2026 Technical Steering Committee Election
            num_winners: 9
            poll_comment_prompts:
                - prompt: Please provide any additional feedback
                - prompt: Please provide any additional feedback
                - prompt: Please provide any additional feedback
                - prompt: Please provide any additional feedback
            poll_questions:
                - choices:
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                  type: single_choice
                - choices:
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                  type: single_choice
                - choices:
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                  type: single_choice
                - choices:
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                    - choice_id: f4bc3849-65e4-4b3a-aad4-35ca6b2faff0
                      choice_text: John Doe
                  prompt: Who should be elected to the TSC?
                  question_id: 71afec48-fb7f-4c4d-a85a-ceca6100727f
                  type: single_choice
            poll_type: condorcet_irv
            project_uid: a09P000000DsCBuIRT
            pseudo_anonymity: true
            quorum_percentage: 50
            winning_threshold_percentage: 51
        required:
            - name
            - description
            - end_time
            - poll_questions
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: |-
            Heimdall JWT authorization

            **Security Scopes**:
              * `read:projects`: Read project data
              * `manage:projects`: Manage projects
              * `manage:voting`: Manage voting
        name: Authorization
        in: header
